CREATE DATABASE products;

USE products;

CREATE TABLE product (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(100) NULL DEFAULT NULL,
  slogan VARCHAR(150) NULL DEFAULT NULL,
  description VARCHAR(300) NULL DEFAULT NULL,
  category VARCHAR(100) NULL DEFAULT NULL,
  default_price INTEGER NULL DEFAULT NULL,
);

-- DROP TABLE IF EXISTS `features`;

CREATE TABLE features (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  product_id INTEGER NOT NULL,
  feature VARCHAR(100) NULL DEFAULT NULL,
  value VARCHAR(100) NULL DEFAULT NULL,
);

-- DROP TABLE IF EXISTS `styles`;

CREATE TABLE styles (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  productId INTEGER NULL DEFAULT NULL,
  name VARCHAR(100) NULL DEFAULT NULL,
  sale_price INTEGER NULL DEFAULT NULL,
  original_price INTEGER NULL DEFAULT NULL,
  default_style BOOLEAN NULL DEFAULT NULL,
);

-- DROP TABLE IF EXISTS `photos`;

CREATE TABLE photos (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  styleId INTEGER NULL DEFAULT NULL,
  url VARCHAR(300) NULL DEFAULT NULL,
  thumbnail_url VARCHAR(300) NULL DEFAULT NULL,
);

-- DROP TABLE IF EXISTS skus;

CREATE TABLE skus (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  styleId INTEGER NULL DEFAULT NULL,
  quantity INTEGER NULL DEFAULT NULL,
  size VARCHAR(3) NULL DEFAULT NULL,
);

-- DROP TABLE IF EXISTS `relatedProducts`;

CREATE TABLE related (
  id INTEGER NULL AUTO_INCREMENT PRIMARY KEY DEFAULT NULL,
  current_product_id INTEGER NULL DEFAULT NULL,
  related_product_id INTEGER NULL DEFAULT NULL,
);

